services:
  app:
    build: .
    ports: 
      - "8000:80"
    volumes:
      - .:/var/www/html
  db: 
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: softline
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d
volumes:
  dbdata:
  